name: helth_controller
description: "A new Flutter project."

publish_to: 'none'
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  fl_chart: ^0.69.2
  sqflite: ^2.0.0+4
  path: ^1.8.3


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/main_icon.png
    - assets/images/steps.png
    - assets/images/heart.png
    - assets/images/weight.png
    - assets/images/sleep.png
    - assets/images/temperature.png
    - assets/images/pressure.png

  fonts:
  - family: WorkSans
    fonts:
      - asset: assets/fonts/WorkSans-VariableFont_wght.ttf

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
